[project]
name = "steam"
version = "1.6.1"
description = "Module for interacting with various Steam features"
readme = "README.rst"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=5.5.0",
    "gevent-eventemitter>=2.1",
    "gevent>=24.11.1",
    "pycryptodomex>=3.21.0",
    "requests>=2.32.3",
    "vdf",
    "wsproto>=1.2.0",
    "protobuf>=5.29.0",
]

[dependency-groups]
dev = [
    "coverage>=7.6.8",
    "coveralls>=4.0.1",
    "mock>=5.1.0",
    "pytest-cov>=6.0.0",
    "pyyaml>=6.0.2",
    "ruff>=0.8.1",
    "vcrpy>=6.0.2",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources]
vdf = { git = "https://github.com/solsticegamestudios/vdf.git", rev = "v4.0" }

[tool.ruff]
preview = true
fix = true
exclude = ["src/steam/protobufs"]

[tool.ruff.lint]
select = ["E", "W", "F", "N", "I"]

#[tool.ruff.lint.per-file-ignores]
#"src/steam/protobufs/*" = ["ALL"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
