version: 3

tasks:
  init:
    desc: install python dependancies
    cmd: uv sync

  check:
    aliases:
      - default
    cmd: uv run -m ruff check {{ .CLI_ARGS }} .

  format:
    aliases:
      - fmt
    cmd: uv run -m ruff format {{ .CLI_ARGS }} .

  test:
    desc: pytest
    cmds:
      - uv run -m coverage erase
      - PYTHONHASHSEED=0 uv run -m pytest --cov-config=pyproject.toml --cov=steam --tb=short {{ .CLI_ARGS }} tests

  clean:
    cmd: uv run -m tools.clean

  dist:
    desc: build source distribution
    cmds:
      - task: clean
      - uv build --sdist

  upload:
    desc: upload to pypi
    cmds:
      - task: dist
      - twine upload -r pypi dist/*

  protobuf_fetch:
    aliases:
      - pb_fetch
    desc: fetch protobufs from SteamRE
    cmd: uv run -m tools.protobuf.fetch

  protobuf_compile:
    aliases:
      - pb_compile
    desc: compile with protoc
    cmd: uv run -m tools.protobuf.compile

  protobuf_clear:
    aliases:
      - pb_clear
    desc: removes *.proto
    cmd: uv run -m tools.protobuf.clear

  protobuf_services:
    aliases:
      - pb_services
    cmd: uv run -m tools.protobuf.services

  protobuf_generate_enums:
    aliases:
      - pb_gen_enums
    cmd: uv run -m tools.protobuf.generate_enums

  protobuf_update:
    aliases:
      - pb_update
    desc: pb_fetch + pb_compile
    cmds:
      - task: protobuf_clear
      - task: protobuf_fetch
      - task: protobuf_compile
      - task: protobuf_services
      - task: protobuf_generate_enums
